### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by madsri2** [iatacodes/nodejs-sdk#1]
When using this package as is (which uses https to talk to iatacode.org), I see the following error:

Error: Error: unable to verify the first certificate

When directly trying to curl, I get the following error:

curl 'https://iatacodes.org/api/v6/autocomplete?query=lisbon&api_key=API_KEY

curl: (60) Peer's Certificate issuer is not recognized.
....

Looks like there is an issue with certs on the server side?

Madhu

**Comment by iatacodes** [comment]
Please, check it again
curl "https://iatacodes.org/api/v6/autocomplete?api_key=YOUR-API-KEY&query=lisbon"
possible it can happen, cause certificate was changed.
